max_width = 80
hard_tabs = false
tab_spaces = 2
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
#brace_style = "AlwaysNextLine"
#format_strings = true
newline_style = "Unix"
#normalize_comments = true
style_edition = "2024"