name: app-build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            build-script: ./build-linux.sh
          - os: macos-latest
            build-script: ./build-macos.sh
          - os: windows-latest
            build-script: .\build-windows.bat

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Make build scripts executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ${{ matrix.build-script }}
      - name: Build with OS-specific script
        run: ${{ matrix.build-script }}
      - name: Run tests
        run: cargo test --verbose
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binaries
          path: build/
