name: on_action.yml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-commit:
    uses: ./.github/workflows/commit-validation.yml

  security-audit:
    uses: ./.github/workflows/security-audit.yml

  release:
    uses: ./.github/workflows/release.yml

  build:
    needs: release
    if: needs.release.outputs.released == 'true'
    uses: ./.github/workflows/build-multiarch.yml
    with: # 👈 Passa i parametri al workflow chiamato
      version: ${{ needs.release.outputs.version }}
      released: ${{ needs.release.outputs.released }}
