name: on_action.yml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-commit:
    uses: ./.github/workflows/commit-validation.yml

  security-audit:
    uses: ./.github/workflows/security-audit.yml

  release:
    uses: ./.github/workflows/release.yml

  # 👈 Job di debug per vedere gli output
  debug-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Debug Release Outputs
        run: |
          echo "Released: '${{ needs.release.outputs.released }}'"
          echo "Version: '${{ needs.release.outputs.version }}'"
          echo "Released type: ${{ type(needs.release.outputs.released) }}"


  build:
    needs: release
    if: needs.release.outputs.released == 'true'
    uses: ./.github/workflows/build-multiarch.yml
    with: # 👈 Passa i parametri al workflow chiamato
      version: ${{ needs.release.outputs.version }}
      released: ${{ needs.release.outputs.released }}
