name: Security Audit
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  push:
    branches: [ "main" ]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
jobs:
  security_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Test | Security Audit
        uses: EmbarkStudios/cargo-deny-action@v2.0.11
        with:
          command: check ${{ matrix.checks }}
